### PR TITLE
doc: add a simple tutorial to guide users

### LINKED ISSUE #62: [Documentation/user guide] How to run the custom kube-scheduler with wasm extension
**What happened**:
Currently, there is no quick start guide to get started on kube-scheduler-was-extension. A quick start guide should help in following ways: 
- Easy to get a hands on experience around how wasm extension works.
- Easy for new developers to get onboarded to the project. 

**What you expected to happen**:
A quick start guide should exist. 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- kube-scheduler-wasm-extension version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #88: [Documentation/contributor guide] The basic folder architecture
/kind document

Document which folder has what. No need to describe all, describing main folders is enough.

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

add a simple tutorial to guide users.

#### Which issue(s) this PR fixes:

Fixes #62
Fixes #88

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### What are the benchmark results of this change?

```benchstat
n/a
```

### CODE REVIEW

**Comment by Gekko0114** [comment]
/lgtm
Thanks!

**Comment by Gekko0114** [comment]
Ah sorry, I didn't notice that it will be merged after adding lgtm label. I should add lgtm label after @utam0k reviewing this.

**Comment by utam0k** [comment]
/lgtm

Thanks

**Pull request merged**
