### PR TITLE
have a label tide/merge-method-squash in all PRs

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

have a label `tide/merge-method-squash` in all PRs via PR template.
Instead of asking squash for authors, we can ask the bot to do squash merge.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### What are the benchmark results of this change?

```benchstat

```

### CODE REVIEW

**Review by codefromthecrypt — APPROVED** [review]
does this limit the message to only the title of PR? GitHub has this feature now, and it is a lot nicer that a list of "broke, fixed, fuzz" etc.

**Comment by anuraaga** [comment]
If the bot is using the GitHub API it probably reflects the repo settings, so it may be good to confirm what they look like. The setting is around here
image

**Comment by sanposhiho** [comment]
> does this limit the message to only the title of PR? GitHub has this feature now, and it is a lot nicer that a list of "broke, fixed, fuzz" etc.

It also has the commits like https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/commit/f801a888e637e897ddca822ae213780e30a89030

**Comment by sanposhiho** [comment]
I just changed the setting to allow only squash merging, let's see how the bot works in another PR

Screenshot 2023-06-09 at 12 44 39

**Comment by codefromthecrypt** [comment]
Screenshot 2023-06-09 at 11 53 59

maybe re-kick the action?

**Comment by sanposhiho** [comment]
Well, seems we need to have the label anyway then to let the bot merge the PR. 😓

**Comment by anuraaga** [comment]
@sanposhiho I'm not familiar with the bot but my guess would be you need to add `/label tide/merge-method-squash` to this PR itself to switch it to non-merge mode

**Comment by kerthcet** [comment]
My concern is independent commits will also be squashed. Prefer to label that manually.

**Comment by codefromthecrypt** [comment]
> My concern is independent commits will also be squashed. Prefer to label that manually.

if we do well one PR is small enough that independent commits aren't needed. how about it?

**Comment by sanposhiho** [comment]
Have a chat with @codefromthecrypt, let's keep as it is now. 
I'd close this.

/close

**Pull request closed without merging**
