### PR TITLE
add: add the copyright header

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR adds the copyright header, which we usually add even in the sub projects.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by codefromthecrypt — APPROVED** [review]

**Comment by kerthcet** [comment]
Maybe the folder migration first https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/18 for you have to modify again. but I'm ok with both approaches.

**Comment by kerthcet** [comment]
/lgtm
/approve
/hold

Leave it to you.

**Comment by sanposhiho** [comment]
@kerthcet Sorry for bothering you again, PTAL 🙏

**Comment by kerthcet** [comment]
My pleasure.
/lgtm

**Pull request merged**
