### PR TITLE
Reuse call stack when invoking filter

### PR DESCRIPTION
**Pull request by anuraaga**
#### What type of PR is this?

/label tide/merge-method-squash

#### What this PR does / why we need it:

Preallocates a call stack for wasm invocation to reduce allocations during the filter hot path. This improves performance of function invocation a little bit.

#### Special notes for your reviewer:

This project may not be at a stage for such small optimizations so no need to proceed if so - I saw some perf work happening so figured it may help to send it

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### What are the benchmark results of this change?

```benchstat
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/kube-scheduler-wasm-extension/internal/e2e
                                            │   old.txt   │              new.txt              │
                                            │   sec/op    │   sec/op     vs base              │
PluginFilter/noop/params:_small-10            201.1n ± 3%   190.6n ± 3%  -5.17% (p=0.002 n=6)
PluginFilter/noop/params:_real-10             200.9n ± 3%   189.5n ± 2%  -5.67% (p=0.002 n=6)
PluginFilter/filter-simple/params:_small-10   8.588µ ± 3%   8.249µ ± 4%  -3.95% (p=0.041 n=6)
PluginFilter/filter-simple/params:_real-10    58.85µ ± 3%   59.30µ ± 2%       ~ (p=0.589 n=6)
geomean                                       2.126µ        2.050µ       -3.54%
```

### CODE REVIEW

**Review by codefromthecrypt — APPROVED** [review]
great idea. the guest is only used sequentially, so any functions we need we can pre-size the buffer

**Review by sanposhiho — APPROVED** [review]
/approve
/lgtm

**Comment by codefromthecrypt** [comment]
thanks for lighting turn-around as this drifts my local stuff and I was a bit anxious when it would land. All good!

**Pull request merged**
